//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaleOfTwoWastelands.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaleOfTwoWastelands.Properties.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exist. Would you like to overwrite them?.
        /// </summary>
        internal static string AlreadyExistOverwritePrompt {
            get {
                return ResourceManager.GetString("AlreadyExistOverwritePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is easiest to install via a mod manager like {1}. Manual installation is possible but not suggested.
        ///
        ///Would like the installer to automatically build FOMODs?.
        /// </summary>
        internal static string BuildFOMODsPrompt {
            get {
                return ResourceManager.GetString("BuildFOMODsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build FOMODs?.
        /// </summary>
        internal static string BuildFOMODsQuestion {
            get {
                return ResourceManager.GetString("BuildFOMODsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceling....
        /// </summary>
        internal static string CancelingWait {
            get {
                return ResourceManager.GetString("CancelingWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for required files.
        /// </summary>
        internal static string CheckingRequiredFiles {
            get {
                return ResourceManager.GetString("CheckingRequiredFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while installing:
        ///{0}.
        /// </summary>
        internal static string ErrorWhileInstalling {
            get {
                return ResourceManager.GetString("ErrorWhileInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors occurred while patching {0}.
        /// </summary>
        internal static string ErrorWhilePatching {
            get {
                return ResourceManager.GetString("ErrorWhilePatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extracting {0}.
        /// </summary>
        internal static string Extracting {
            get {
                return ResourceManager.GetString("Extracting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download NVSE..
        /// </summary>
        internal static string FailedDownloadNvse {
            get {
                return ResourceManager.GetString("FailedDownloadNvse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to extract NVSE..
        /// </summary>
        internal static string FailedExtractNvse {
            get {
                return ResourceManager.GetString("FailedExtractNvse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save path &quot;{0}&quot; to {1}.
        /// </summary>
        internal static string FailedToSavePath {
            get {
                return ResourceManager.GetString("FailedToSavePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallout 3.
        /// </summary>
        internal static string Fallout3 {
            get {
                return ResourceManager.GetString("Fallout3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fallout New Vegas.
        /// </summary>
        internal static string FalloutNewVegas {
            get {
                return ResourceManager.GetString("FalloutNewVegas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; already exists.
        /// </summary>
        internal static string FileAlreadyExists {
            get {
                return ResourceManager.GetString("FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Already Exists.
        /// </summary>
        internal static string FileAlreadyExistsTitle {
            get {
                return ResourceManager.GetString("FileAlreadyExistsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; does not exist.
        /// </summary>
        internal static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        internal static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install cancelled due to NVSE requirement.
        /// </summary>
        internal static string InstallCancelledNvse {
            get {
                return ResourceManager.GetString("InstallCancelledNvse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been installed successfully..
        /// </summary>
        internal static string InstalledSuccessfully {
            get {
                return ResourceManager.GetString("InstalledSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is an invalid 7z archive..
        /// </summary>
        internal static string Invalid7zArchive {
            get {
                return ResourceManager.GetString("Invalid7zArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be run as Administrator..
        /// </summary>
        internal static string MustBeElevated {
            get {
                return ResourceManager.GetString("MustBeElevated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NVSE found.
        /// </summary>
        internal static string NvseFound {
            get {
                return ResourceManager.GetString("NvseFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Vegas Script Extender (NVSE) was not found, but is required to play A Tale of Two Wastelands.
        ///
        ///Would you like to install NVSE?.
        /// </summary>
        internal static string NvseInstallPrompt {
            get {
                return ResourceManager.GetString("NvseInstallPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NVSE was installed successfully..
        /// </summary>
        internal static string NvseInstallSuccessful {
            get {
                return ResourceManager.GetString("NvseInstallSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NVSE missing.
        /// </summary>
        internal static string NvseMissing {
            get {
                return ResourceManager.GetString("NvseMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NVSE must be installed before playing!.
        /// </summary>
        internal static string NvseMustBeInstalled {
            get {
                return ResourceManager.GetString("NvseMustBeInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite Files.
        /// </summary>
        internal static string OverwriteFiles {
            get {
                return ResourceManager.GetString("OverwriteFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsed NVSE link: {0}.
        /// </summary>
        internal static string ParsedNvseLink {
            get {
                return ResourceManager.GetString("ParsedNvseLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceeding without NVSE..
        /// </summary>
        internal static string ProceedingWithoutNvse {
            get {
                return ResourceManager.GetString("ProceedingWithoutNvse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists. Rebuild?.
        /// </summary>
        internal static string RebuildPrompt {
            get {
                return ResourceManager.GetString("RebuildPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requesting NVSE page at {0}.
        /// </summary>
        internal static string RequestingNvsePage {
            get {
                return ResourceManager.GetString("RequestingNvsePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible.
        /// </summary>
        internal static string RightSaidFred {
            get {
                return ResourceManager.GetString("RightSaidFred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOMM.
        /// </summary>
        internal static string SuggestedModManager {
            get {
                return ResourceManager.GetString("SuggestedModManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tale of Two Wastelands.
        /// </summary>
        internal static string TTW {
            get {
                return ResourceManager.GetString("TTW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An uncaught exception occurred and the program will now exit. Please submit a crash report with your installation log..
        /// </summary>
        internal static string UncaughtExceptionMessage {
            get {
                return ResourceManager.GetString("UncaughtExceptionMessage", resourceCulture);
            }
        }
    }
}
