//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaleOfTwoWastelands.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Paths {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Paths() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaleOfTwoWastelands.Properties.Paths", typeof(Paths).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resources.
        /// </summary>
        internal static string AssetsDir {
            get {
                return ResourceManager.GetString("AssetsDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Files.
        /// </summary>
        internal static string MainDir {
            get {
                return ResourceManager.GetString("MainDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaleOfTwoWastelands_Main.fomod.
        /// </summary>
        internal static string MainFOMOD {
            get {
                return ResourceManager.GetString("MainFOMOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nvse_loader.exe.
        /// </summary>
        internal static string NvseFile {
            get {
                return ResourceManager.GetString("NvseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://nvse.silverlock.org/.
        /// </summary>
        internal static string NvseLink {
            get {
                return ResourceManager.GetString("NvseLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://nvse.silverlock.org/download/*.7z.
        /// </summary>
        internal static string NvseSearchPattern {
            get {
                return ResourceManager.GetString("NvseSearchPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional Files.
        /// </summary>
        internal static string OptDir {
            get {
                return ResourceManager.GetString("OptDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaleOfTwoWastelands_Options.fomod.
        /// </summary>
        internal static string OptFOMOD {
            get {
                return ResourceManager.GetString("OptFOMOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7Zip.
        /// </summary>
        internal static string SevenZipBinaries {
            get {
                return ResourceManager.GetString("SevenZipBinaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7z.dll.
        /// </summary>
        internal static string SevenZipX32 {
            get {
                return ResourceManager.GetString("SevenZipX32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7z64.dll.
        /// </summary>
        internal static string SevenZipX64 {
            get {
                return ResourceManager.GetString("SevenZipX64", resourceCulture);
            }
        }
    }
}
