//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaleOfTwoWastelands.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaleOfTwoWastelands.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Fallout - Meshes&quot;:&quot;Fallout3 - Meshes&quot;,&quot;Fallout - Misc&quot;:&quot;Fallout3 - Misc&quot;,&quot;Fallout - Sound&quot;:&quot;Fallout3 - Sound&quot;,&quot;Fallout - Textures&quot;:&quot;Fallout3 - Textures&quot;,&quot;Fallout - MenuVoices&quot;:&quot;Fallout3 - MenuVoices&quot;,&quot;Fallout - Voices&quot;:&quot;Fallout3 - Voices&quot;,&quot;Anchorage - Main&quot;:&quot;Anchorage - Main&quot;,&quot;Anchorage - Sounds&quot;:&quot;Anchorage - Sounds&quot;,&quot;ThePitt - Main&quot;:&quot;ThePitt - Main&quot;,&quot;ThePitt - Sounds&quot;:&quot;ThePitt - Sounds&quot;,&quot;BrokenSteel - Main&quot;:&quot;BrokenSteel - Main&quot;,&quot;BrokenSteel - Sounds&quot;:&quot;BrokenSteel - Sounds&quot;,&quot;PointLookout - Main&quot;:&quot;PointLoo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BuildableBSAs {
            get {
                return ResourceManager.GetString("BuildableBSAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Fallout3 - Main.bsa&quot;:[&quot;Fallout - Meshes.bsa&quot;,&quot;Fallout - Misc.bsa&quot;,&quot;Fallout - Textures.bsa&quot;],&quot;Fallout3 - Sounds.bsa&quot;:[&quot;Fallout - MenuVoices.bsa&quot;,&quot;Fallout - Sound.bsa&quot;,&quot;Fallout - Voices.bsa&quot;],&quot;Fallout3 - DLC.bsa&quot;:[&quot;Anchorage - Main.bsa&quot;,&quot;Anchorage - Sounds.bsa&quot;,&quot;ThePitt - Main.bsa&quot;,&quot;ThePitt - Sounds.bsa&quot;,&quot;BrokenSteel - Main.bsa&quot;,&quot;BrokenSteel - Sounds.bsa&quot;,&quot;PointLookout - Main.bsa&quot;,&quot;PointLookout - Sounds.bsa&quot;,&quot;Zeta - Main.bsa&quot;,&quot;Zeta - Sounds.bsa&quot;]}.
        /// </summary>
        public static string CheckedBSAs {
            get {
                return ResourceManager.GetString("CheckedBSAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&quot;Fallout3.esm&quot;,&quot;Anchorage.esm&quot;,&quot;ThePitt.esm&quot;,&quot;BrokenSteel.esm&quot;,&quot;PointLookout.esm&quot;,&quot;Zeta.esm&quot;].
        /// </summary>
        public static string CheckedESMs {
            get {
                return ResourceManager.GetString("CheckedESMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Installer_Icon {
            get {
                object obj = ResourceManager.GetObject("Installer_Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;sound\\voice\\fallout3.esm\\playervoicemale&quot;:&quot;PlayerVoice\\sound\\voice\\falloutnv.esm\\playervoicemale&quot;,&quot;sound\\voice\\fallout3.esm\\playervoicefemale&quot;:&quot;PlayerVoice\\sound\\voice\\falloutnv.esm\\playervoicefemale&quot;}.
        /// </summary>
        public static string VoicePaths {
            get {
                return ResourceManager.GetString("VoicePaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sound\voice.
        /// </summary>
        public static string VoicePrefix {
            get {
                return ResourceManager.GetString("VoicePrefix", resourceCulture);
            }
        }
    }
}
