//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Drawing;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace Resources.Properties
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    public class Resources
    {

        private static ResourceManager resourceMan;

        private static CultureInfo resourceCulture;

        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    ResourceManager temp = new ResourceManager("Resources.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        public static CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {&quot;Fallout - Meshes&quot;:&quot;Fallout3 - Meshes&quot;,&quot;Fallout - Misc&quot;:&quot;Fallout3 - Misc&quot;,&quot;Fallout - Sound&quot;:&quot;Fallout3 - Sound&quot;,&quot;Fallout - Textures&quot;:&quot;Fallout3 - Textures&quot;,&quot;Fallout - MenuVoices&quot;:&quot;Fallout3 - MenuVoices&quot;,&quot;Fallout - Voices&quot;:&quot;Fallout3 - Voices&quot;,&quot;Anchorage - Main&quot;:&quot;Anchorage - Main&quot;,&quot;Anchorage - Sounds&quot;:&quot;Anchorage - Sounds&quot;,&quot;ThePitt - Main&quot;:&quot;ThePitt - Main&quot;,&quot;ThePitt - Sounds&quot;:&quot;ThePitt - Sounds&quot;,&quot;BrokenSteel - Main&quot;:&quot;BrokenSteel - Main&quot;,&quot;BrokenSteel - Sounds&quot;:&quot;BrokenSteel - Sounds&quot;,&quot;PointLookout - Main&quot;:&quot;PointLoo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BuildableBSAs
        {
            get
            {
                return ResourceManager.GetString("BuildableBSAs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {&quot;Fallout3 - Main.bsa&quot;:[&quot;Fallout - Meshes.bsa&quot;,&quot;Fallout - Misc.bsa&quot;,&quot;Fallout - Textures.bsa&quot;],&quot;Fallout3 - Sounds.bsa&quot;:[&quot;Fallout - MenuVoices.bsa&quot;,&quot;Fallout - Sound.bsa&quot;,&quot;Fallout - Voices.bsa&quot;],&quot;Fallout3 - DLC.bsa&quot;:[&quot;Anchorage - Main.bsa&quot;,&quot;Anchorage - Sounds.bsa&quot;,&quot;ThePitt - Main.bsa&quot;,&quot;ThePitt - Sounds.bsa&quot;,&quot;BrokenSteel - Main.bsa&quot;,&quot;BrokenSteel - Sounds.bsa&quot;,&quot;PointLookout - Main.bsa&quot;,&quot;PointLookout - Sounds.bsa&quot;,&quot;Zeta - Main.bsa&quot;,&quot;Zeta - Sounds.bsa&quot;]}.
        /// </summary>
        public static string CheckedBSAs
        {
            get
            {
                return ResourceManager.GetString("CheckedBSAs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [&quot;Fallout3.esm&quot;,&quot;Anchorage.esm&quot;,&quot;ThePitt.esm&quot;,&quot;BrokenSteel.esm&quot;,&quot;PointLookout.esm&quot;,&quot;Zeta.esm&quot;].
        /// </summary>
        public static string CheckedESMs
        {
            get
            {
                return ResourceManager.GetString("CheckedESMs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static Icon Installer_Icon
        {
            get
            {
                object obj = ResourceManager.GetObject("Installer_Icon", resourceCulture);
                return ((Icon)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {&quot;sound\\voice\\fallout3.esm\\playervoicemale&quot;:&quot;PlayerVoice\\sound\\voice\\falloutnv.esm\\playervoicemale&quot;,&quot;sound\\voice\\fallout3.esm\\playervoicefemale&quot;:&quot;PlayerVoice\\sound\\voice\\falloutnv.esm\\playervoicefemale&quot;}.
        /// </summary>
        public static string VoicePaths
        {
            get
            {
                return ResourceManager.GetString("VoicePaths", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to sound\voice.
        /// </summary>
        public static string VoicePrefix
        {
            get
            {
                return ResourceManager.GetString("VoicePrefix", resourceCulture);
            }
        }
    }
}
